app/models/user.py
from flask_login import UserMixin
from passlib.hash import pbkdf2_sha256 as sha256

from app import db


class UserModel(db.Model, UserMixin):
    __tablename__ = 'users'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(120), unique=True, nullable=False)
    password = db.Column(db.String, nullable=False)
    type = db.Column(db.String, nullable=False)
    info = db.Column(db.JSON)

    def __init__(self, username, password):
        self.username = username
        self.password = sha256.hash(password)
        self.type = 'normal'

    # Helper Functions
    @classmethod
    def username_available(cls, username):
        user = cls.get_by_username(username)
        if not user:
            return True
        else:
            return False

    # Representations
    def __repr__(self):
        return f'ID: {self.id} USERNAME: {self.username}'

    def jsonify_dict(self):
        return {'id': self.id, 'username': self.username, 'info': self.info}

    def check_password(self, password):
        return sha256.verify(password, self.password)

    # Mutate instance
    def change_username(self, username):
        self.username = username
        return self

    def change_password(self, password):
        self.password = sha256.hash(password)
        return self

    def update_info(self, info):
        self.info = info
        return self

    # Mutate database
    def add_user(self):
        db.session.add(self)
        db.session.commit()
        return self

    def delete_user(self):
        db.session.delete(self)
        db.session.commit()
        return self

    # Database accessors
    @classmethod
    def get_all(cls):
        return cls.query.order_by(cls.username).all()

    @classmethod
    def get_by_id(cls, user_id):
        return cls.query.get(user_id)

    @classmethod
    def get_by_username(cls, username):
        return cls.query.filter_by(username=username).first()

app/views/users.py
from flask import Blueprint, render_template, flash, redirect, url_for
from flask_login import login_required
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired

from app.models.user import UserModel

admin_users = Blueprint('admin_users', __name__, url_prefix='/admin-users')


class NewUserForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    submit = SubmitField('New User')


@admin_users.route('/', methods=['GET', 'POST'])
@login_required
def all_users():
    form = NewUserForm()
    users = UserModel.get_all()

    if form.validate_on_submit():
        if UserModel.username_available(form.username.data):
            user = UserModel(form.username.data, 'temppassword').add_user()
            return redirect(url_for('admin_users.edit', user_id=user.id))
        flash('Username already in use.')

    return render_template('users/all.html', users=users, form=form)


@admin_users.route('/<user_id>')
@login_required
def profile(user_id):
    user = UserModel.get_by_id(user_id)

    return render_template('users/profile.html', user=user)


class UserEditForm(FlaskForm):
    username = StringField('Username')
    password = PasswordField('Password')
    submit = SubmitField('Change User Data')


@admin_users.route('/edit/<user_id>', methods=['GET', 'POST'])
@login_required
def edit(user_id):
    user = UserModel.get_by_id(user_id)
    form = UserEditForm(
        username=user.username
    )

    if form.validate_on_submit():
        if form.username.data != user.username:
            flash(f'User #{user.id}\'s name has been changed.')
            user.change_username(form.username.data)

        if form.password.data != "":
            flash(f'User #{user.id}\'s password has been changed.')
            user.change_password(form.password.data)

        user.add_user()
        return redirect(url_for('admin_users.profile', user_id=user_id))

    return render_template('users/edit.html', user=user, form=form)


@admin_users.route('/delete/<user_id>')
@login_required
def delete(user_id):
    user = UserModel.get_by_id(user_id)
    if user.type != 'super':
        user.delete_user()
        flash(f'User #{user_id} has been deleted.')
    else:
        flash(f'User #{user_id} can\'t be deleted')

    return redirect(url_for('admin_users.all_users'))

app/templates/users/all.html
{% extends 'layout.html' %}

{% block content %}
<div class="container-fluid">
  <div class="row justify-content-lg-around">
    <div class="col-auto">
      <h2 class="text-center">All Users</h2>
      {% for user in users %}
      <div class="d-flex flex-row justify-content-between my-2">
        <div class="mr-4">
          <h4>
            <a href="{{ url_for('admin_users.profile', user_id=user.id) }}">
              {{ user.username }}
            </a>
          </h4>
        </div>

        <div class="btn-toolbar">
          <a class="btn btn-sm btn-secondary" href="{{ url_for('admin_users.edit', user_id=user.id) }}">Edit</a>
          <a class="btn btn-sm btn-danger" href="{{ url_for('admin_users.delete', user_id=user.id) }}">Delete</a>
        </div>
      </div>
      {% endfor %}
    </div>

    <form class="col-3" action="" method="post">
      {{ form.hidden_tag() }}
      <h2 class="text-center">New User</h2>
      <div class="form-group">
        {{ form.username(class="form-control") }}
      </div>

      <div class="form-group text-center">
        {{ form.submit(class="btn btn-sm btn-primary") }}
      </div>
    </form>
  </div>

</div>
{% endblock content %}

app/templates/users/edit.html
{% extends 'layout.html' %}

{% block content %}
<form class="container" action="" method="post">
  {{ form.hidden_tag() }}
  <h2>Editing User #{{ user.id }}</h2>

  <div class="form-group">
    {{ form.username.label }}
    {{ form.username(class="form-control") }}
  </div>

  <div class="form-group">
    {{ form.password.label }}
    {{ form.password(class="form-control") }}
  </div>

  <div class="form-group">
    {{ form.submit(class="btn btn-primary") }}
  </div>
</form>
{% endblock content %}

app/templates/users/profile.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col">
      <h2>{{ user.username }}</h2>
    </div>

    <div class="col">
      <div class="btn-toolbar">
        <a class="btn btn-sm btn-secondary" href="{{ url_for('admin_users.edit', user_id=user.id) }}">Edit User</a>
        <a class="btn btn-sm btn-danger" href="{{ url_for('admin_users.delete', user_id=user.id) }}">Delete User</a>
      </div>
    </div>
  </div>
  <p>Character list will be here</p>
</div>
{% endblock content %}