app/models/character.py
from app import db


class CharacterModel(db.Model):
    __tablename__ = 'characters'
    id = db.Column(db.Integer, primary_key=True)
    owner_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    viewers = db.Column(db.JSON)
    name = db.Column(db.String(50), index=True)
    lore = db.Column(db.JSON)
    stats = db.Column(db.JSON)
    abilities = db.Column(db.JSON)

    def __init__(self, owner_id):
        self.owner_id = owner_id

    # Representations
    def __repr__(self):
        return f'ID: {self.id} OWNER: {self.owner_id} NAME: {self.name}'

    def jsonify_dict(self):
        return {
            'id': self.id,
            'ownerId': self.owner_id,
            'viewers': self.viewers,
            'name': self.name,
            'lore': self.lore,
            'stats': self.stats,
            'abilities': self.abilities
        }

    # Mutate entity methods
    def patch_from_json(self, data):
        if 'viewers' in data:
            if data['viewers']:
                self.viewers = [viewer for viewer in data['viewers'] if viewer != self.owner_id]

        if 'name' in data:
            self.name = data['name']

        if 'lore' in data:
            self.lore = data['lore']

        if 'stats' in data:
            self.stats = data['stats']

        if 'abilities' in data:
            self.abilities = data['abilities']

        return self

    # Mutate database methods
    def add_character(self):
        db.session.add(self)
        db.session.commit()
        return self

    def delete_character(self):
        db.session.delete(self)
        db.session.commit()
        return self

    # Database access methods
    @classmethod
    def get_by_id(cls, id):
        return cls.query.get(id)

    @classmethod
    def get_all(cls):
        return cls.query.order_by(cls.name).all()

    @classmethod
    def get_all_by_owner(cls, owner_id):
        return cls.query.filter_by(owner_id=owner_id).order_by(cls.name).all()

    @classmethod
    def get_all_by_viewer(cls, viewer_id):
        characters = []
        for character in cls.query.order_by(cls.name).all():
            if character.viewers:
                if viewer_id in character.viewers:
                    characters.append(character)
        return characters

app/views/character.py
from flask import Blueprint, flash, render_template, redirect, url_for, jsonify
from flask_login import login_required
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, SubmitField
from wtforms.validators import DataRequired

from app.models.user import UserModel
from app.models.character import CharacterModel

admin_character = Blueprint('admin_character', __name__, url_prefix='/admin-character')


class NewCharacterForm(FlaskForm):
    owner = SelectField('Owner ID', coerce=int)
    submit = SubmitField('New Character')


@admin_character.route('/', methods=['GET', 'POST'])
@login_required
def all_characters():
    form = NewCharacterForm()
    form.owner.choices = [(user.id, user.username) for user in UserModel.get_all()]
    characters = CharacterModel.get_all()

    if form.validate_on_submit():
        new_character = CharacterModel(form.owner.data).add_character()
        return redirect(url_for('admin_character.edit', character_id=new_character.id))

    return render_template('character/all.html', characters=characters, form=form)


@admin_character.route('/<character_id>')
@login_required
def profile(character_id):
    character = CharacterModel.get_by_id(character_id)

    return render_template('character/profile.html', character=character)


class CharacterEditForm(FlaskForm):
    owner = SelectField('Owner ID', coerce=int)
    name = StringField('Character Name')
    submit = SubmitField('Submit Changes')


@admin_character.route('/edit/<character_id>', methods=['GET', 'POST'])
@login_required
def edit(character_id):
    character = CharacterModel.get_by_id(character_id)
    form = CharacterEditForm(
        name=character.name
    )
    form.owner.choices = [(user.id, user.username) for user in UserModel.get_all()]
    form.owner.data = character.owner_id

    if form.validate_on_submit():
        if form.owner.data != character.owner_id:
            flash(f'Character #{character_id}\'s owner has been changed.')
            character.owner_id = form.owner.data

        if form.name.data != character.name:
            flash(f'Character #{character_id}\'s name has been changed.')
            character.name = form.name.data

        character.add_character()
        return redirect(url_for('admin_character.profile', character_id=character_id))

    return render_template('character/edit.html', character=character, form=form)


@admin_character.route('/delete/<character_id>')
@login_required
def delete(character_id):
    character = CharacterModel.get_by_id(character_id).delete_character()
    flash(f'Page #{character_id}\'s has been deleted.')
    return redirect(url_for('admin_users.edit', user_id=character.owner_id))


@admin_character.route('/json/<character_id>')
@login_required
def json(character_id):
    character = CharacterModel.get_by_id(character_id)
    return jsonify(character.jsonify_dict())

app/templates/character/all.html
{% extends 'layout.html' %}

{% block content %}
<div class="container-fluid">
  <div class="row justify-content-around">
    <div class="col-auto">
      <h2 class="text-center">All Characters</h2>
      {% for character in characters %}
      <div class="d-flex flex-row justify-content-between my-2">
        <h4 class="mr-4">
          <a href="{{ url_for('admin_character.profile', character_id=character.id) }}">
            {{ character.name }}
          </a>
        </h4>
        <div class="btn-toolbar">
          <a class="btn btn-sm btn-info"
             href="{{ url_for('admin_character.json', character_id=character.id) }}">JSON</a>
          <a class="btn btn-sm btn-secondary" href="{{ url_for('admin_character.edit', character_id=character.id) }}">Edit</a>
          <a class="btn btn-sm btn-danger" href="{{ url_for('admin_character.delete', character_id=character.id) }}">Delete</a>
        </div>
      </div>
      {% endfor %}
    </div>

    <form class="col-4" action="" method="post">
      {{ form.hidden_tag() }}

      <h2 class="text-center">New Character</h2>

      <div class="form-group">
        {{ form.owner.label }}
        {{ form.owner(class="form-control") }}
      </div>

      <div class="form-group text-center">
        {{ form.submit(class="btn btn-primary") }}
      </div>
    </form>
  </div>
</div>
{% endblock content %}

app/templates/character/edit.html
{% extends 'layout.html' %}

{% block content %}
<form class="container" action="" method="post">
  {{ form.hidden_tag() }}
  <h2>Editing Character #{{ character.id }}</h2>

  <div class="form-group">
    {{ form.owner.label }}
    {{ form.owner(class="form-control") }}
  </div>

  <div class="form-group">
    {{ form.name.label }}
    {{ form.name(class="form-control") }}
  </div>

  <div class="form-group">
    {{ form.submit(class="btn btn-primary") }}
  </div>
</form>
{% endblock content %}

app/templates/character/profile.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">
  <h2>{{ character.name }}</h2>

  <h4><strong>Character ID:</strong> {{ character.id }}</h4>

  <h4><strong>Owner ID:</strong> {{ character.owner_id }}</h4>

  <h4><strong>Viewers:</strong> {{ character.viewers }}</h4>

  <h4><strong>Lore:</strong></h4>
  <p>{{ character.lore }}</p>

  <h4><strong>Stats:</strong></h4>
  <p>{{ character.stats }}</p>

  <h4><strong>Abilities:</strong></h4>
  <p>{{ character.abilities }}</p>
</div>
{% endblock content %}