app/models/compendium.py
from app import db


class CompendiumModel(db.Model):
    __tablename__ = 'compendium'
    id = db.Column(db.Integer, primary_key=True)
    owner_id = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
    title = db.Column(db.String, index=True, nullable=False, unique=True)
    content = db.Column(db.String)

    def __init__(self, owner_id, title):
        self.owner_id = owner_id
        self.title = title
        self.content = ""

    # Helper functions
    @classmethod
    def title_available(cls, title):
        poss_page = cls.get_by_title(title)
        if not poss_page:
            return True
        else:
            return False

    # Representation
    def jsonify_dict(self):
        return {
            'id': self.id,
            'ownerId': self.owner_id,
            'title': self.title,
            'content': self.content
        }

    def jsonify_short(self):
        return {
            'id': self.id,
            'ownerId': self.owner_id,
            'title': self.title
        }

    # Mutate entity methods
    def patch_from_json(self, data):
        if 'title' in data:
            self.title = data['title']

        if 'content' in data:
            self.content = data['content']

        return self

    # Mutate database methods
    def add_compendium(self):
        db.session.add(self)
        db.session.commit()
        return self

    def delete_compendium(self):
        db.session.delete(self)
        db.session.commit()
        return self

    # Database access methods
    @classmethod
    def get_by_id(cls, compendium_id):
        return cls.query.get(compendium_id)

    @classmethod
    def get_by_title(cls, compendium_title):
        return cls.query.filter_by(title=compendium_title).first()

    @classmethod
    def get_all(cls):
        return cls.query.order_by(cls.title).all()

    @classmethod
    def get_all_by_owner(cls, owner_id):
        return cls.query.order_by(cls.title).all()

app/views/compendium.py
from flask import Blueprint, flash, render_template, redirect, url_for, jsonify
from flask_login import login_required, current_user
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, FileField, SubmitField
from wtforms.validators import DataRequired

from app.models.compendium import CompendiumModel

admin_compendium = Blueprint('admin_compendium', __name__, url_prefix='/admin-compendium')


class NewCompendiumForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    submit = SubmitField('New Page')


@admin_compendium.route('/', methods=['GET', 'POST'])
@login_required
def all_compendium():
    form = NewCompendiumForm()
    pages = CompendiumModel.get_all()

    if form.validate_on_submit():
        if CompendiumModel.title_available(form.title.data):
            new_page = CompendiumModel(current_user.id, form.title.data).add_compendium()
            return redirect(url_for('admin_compendium.edit', compendium_id=new_page.id))
        flash('Title in use.')

    return render_template('compendium/all.html', form=form, pages=pages)


@admin_compendium.route('/<compendium_id>')
@login_required
def profile(compendium_id):
    page = CompendiumModel.get_by_id(compendium_id)

    return render_template('compendium/profile.html', page=page)


class CompendiumEditForm(FlaskForm):
    title = StringField('Title')
    content = TextAreaField('Content')
    file = FileField('File Content (will replace old content)')
    submit = SubmitField('Submit')


@admin_compendium.route('/edit/<compendium_id>', methods=['GET', 'POST'])
@login_required
def edit(compendium_id):
    page = CompendiumModel.get_by_id(compendium_id)
    form = CompendiumEditForm(
        title=page.title,
        content=page.content
    )

    if form.validate_on_submit():
        if form.title.data != page.title:
            flash(f'Page #{page.id}\'s title has been changed.')
            page.title = form.title.data

        if form.file.data:
            flash(f'Page #{page.id}\'s contents have been replaced with file contents.')

            page.content = form.file.data.read().decode('utf-8')

        elif form.content.data != page.content:
            flash(f'Page #{page.id}\'s content has been changed.')
            page.content = form.content.data

        page.add_compendium()
        return redirect(url_for('admin_compendium.edit', compendium_id=compendium_id))

    return render_template('compendium/edit.html', form=form, page=page)


@admin_compendium.route('/delete/<compendium_id>')
@login_required
def delete(compendium_id):
    CompendiumModel.get_by_id(compendium_id).delete_compendium()
    flash(f'Page #{compendium_id} has been deleted.')
    return redirect(url_for('admin_compendium.all_compendium'))


@admin_compendium.route('/json/<compendium_id>')
@login_required
def json(compendium_id):
    page = CompendiumModel.get_by_id(compendium_id)
    return jsonify(page.jsonify_dict())

app/templates/compendium/all.html
{% extends 'layout.html' %}

{% block content %}
<div class="container-fluid">
  <div class="row justify-content-lg-around">
    <div class="col-auto">
      <h2 class="text-center">All Compendium Pages</h2>
      {% for page in pages %}
      <div class="d-flex flex-row justify-content-between my-2">
        <h4 class="mr-4">
          <a href="{{ url_for('admin_compendium.profile', compendium_id=page.id) }}">
            {{ page.title }}
          </a>
        </h4>

        <div class="btn-toolbar">
          <a class="btn btn-sm btn-info" href="{{ url_for('admin_compendium.json', compendium_id=page.id) }}">JSON</a>
          <a class="btn btn-sm btn-secondary"
             href="{{ url_for('admin_compendium.edit', compendium_id=page.id) }}">Edit</a>
          <a class="btn btn-sm btn-danger"
             href="{{ url_for('admin_compendium.delete', compendium_id=page.id) }}">Delete</a>
        </div>
      </div>
      {% endfor %}
    </div>

    <form class="col-4" action="" method="post">
      {{ form.hidden_tag() }}

      <h2 class="text-center">New Compendium Page</h2>

      <div class="form-group">
        {{ form.title(class="form-control") }}
      </div>

      <div class="form-group text-center">
        {{ form.submit(class="btn btn-primary") }}
      </div>
    </form>
  </div>
</div>
{% endblock content %}

app/templates/compendium/edit.html
{% extends 'layout.html' %}

{% block content %}
<form class="container" action="" method="post" enctype="multipart/form-data">
  {{ form.hidden_tag() }}

  <div class="row">
    <div class="col-8 h2">
      Editing Compendium Page #{{ page.id }}
    </div>

    <div class="col">
      <div class="btn-toolbar">
        <a class="btn btn-primary" href="{{ url_for('admin_compendium.profile', compendium_id=page.id) }}">View</a>
        <a class="btn btn-danger" href="{{ url_for('admin_compendium.delete', compendium_id=page.id) }}">Delete</a>
      </div>
    </div>
  </div>

  <div class="form-group">
    {{ form.title.label }}
    {{ form.title(class="form-control") }}
  </div>

  <div class="form-group">
    {{ form.content.label }}
    {{ form.content(class="form-control", rows="15") }}
  </div>

  <div class="form-group">
    {{ form.file.label }}
    {{ form.file(class="form-control-file") }}
  </div>

  <div class="form-group text-center">
    {{ form.submit(class="btn btn-primary") }}

  </div>
</form>
{% endblock content %}

app/templates/compendium/profile.html
{% extends 'layout.html' %}

{% block content %}
<div class="container">
  {{ page.content | markdown}}
</div>
{% endblock content %}