app/views/character.py
from flask import Blueprint, flash, render_template, redirect, url_for, jsonify
from flask_login import login_required
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, SubmitField
from wtforms.validators import DataRequired

from app.models.user import UserModel
from app.models.character import CharacterModel

admin_character = Blueprint('admin_character', __name__, url_prefix='/admin-character')


class NewCharacterForm(FlaskForm):
    owner = SelectField('Owner ID', coerce=int)
    submit = SubmitField('New Character')


@admin_character.route('/', methods=['GET', 'POST'])
@login_required
def all_characters():
    form = NewCharacterForm()
    form.owner.choices = [(user.id, user.username) for user in UserModel.get_all()]
    characters = CharacterModel.get_all()

    if form.validate_on_submit():
        new_character = CharacterModel(form.owner.data).add_character()
        return redirect(url_for('admin_character.edit', character_id=new_character.id))

    return render_template('character/all.html', characters=characters, form=form)


@admin_character.route('/<character_id>')
@login_required
def profile(character_id):
    character = CharacterModel.get_by_id(character_id)

    return render_template('character/profile.html', character=character)


class CharacterEditForm(FlaskForm):
    owner = SelectField('Owner ID', coerce=int)
    name = StringField('Character Name')
    submit = SubmitField('Submit Changes')


@admin_character.route('/edit/<character_id>', methods=['GET', 'POST'])
@login_required
def edit(character_id):
    character = CharacterModel.get_by_id(character_id)
    form = CharacterEditForm(
        name=character.name
    )
    form.owner.choices = [(user.id, user.username) for user in UserModel.get_all()]
    form.owner.data = character.owner_id

    if form.validate_on_submit():
        if form.owner.data != character.owner_id:
            flash(f'Character #{character_id}\'s owner has been changed.')
            character.owner_id = form.owner.data

        if form.name.data != character.name:
            flash(f'Character #{character_id}\'s name has been changed.')
            character.name = form.name.data

        character.add_character()
        return redirect(url_for('admin_character.profile', character_id=character_id))

    return render_template('character/edit.html', character=character, form=form)


@admin_character.route('/delete/<character_id>')
@login_required
def delete(character_id):
    character = CharacterModel.get_by_id(character_id).delete_character()
    flash(f'Page #{character_id}\'s has been deleted.')
    return redirect(url_for('admin_users.edit', user_id=character.owner_id))


@admin_character.route('/json/<character_id>')
@login_required
def json(character_id):
    character = CharacterModel.get_by_id(character_id)
    return jsonify(character.jsonify_dict())

app/views/main.py
from flask import Blueprint, render_template, redirect, url_for, flash
from flask_login import login_required, login_user, logout_user, current_user
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired

from app.models.user import UserModel

admin_main = Blueprint('admin_main', __name__)


@admin_main.route('/')
def index_reroute():
    return redirect(url_for('admin_main.home'))


@admin_main.route('/admin/')
@login_required
def home():
    return render_template('main/home.html')


class LoginForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')


@admin_main.route('/admin/login/', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('admin_main.home'))

    form = LoginForm()

    if form.validate_on_submit():
        user = UserModel.get_by_username(form.username.data)

        if user is not None and user.check_password(form.password.data) and user.type == 'super':
            login_user(user)
            flash(f'User {user.username} has been logged in.')
            return redirect(url_for('admin_main.home'))

        flash('Incorrect Credentials')
        return redirect(url_for('admin_main.login'))

    return render_template('main/login.html', form=form)


@admin_main.route('/admin/logout/')
@login_required
def logout():
    logout_user()
    return redirect(url_for('admin_main.login'))

app/templates/layout.html
<!DOCTYPE html>
<html lang="en">
{% block head %}
<head>
  <meta charset="UTF-8">
  <title>Depths API</title>
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
</head>
{% endblock head %}

{% block body %}
<body>
{% block navbar %}
<nav class="navbar navbar-dark bg-dark mb-4">
  <a class="navbar-brand" href="{{ url_for('admin_main.home') }}">
    Depths API
  </a>
  {% if current_user.is_authenticated %}
  <ul class="nav justify-content-center">
    <li class="nav-item">
      <a class="btn btn-outline-light" href="{{ url_for('admin_users.all_users') }}">Users</a>
    </li>

    <li class="nav-item">
      <a class="btn btn-outline-light" href="{{ url_for('admin_compendium.all_compendium') }}">Compendium</a>
    </li>
    <li class="nav-item">
      <a class="btn btn-outline-light" href="{{ url_for('admin_character.all_characters') }}">Characters</a>
    </li>
  </ul>
  <a class="btn btn-outline-light" href="{{ url_for('admin_main.logout') }}">
    Logout
  </a>
  {% endif %}
</nav>
{% endblock navbar %}

{% block flash %}
{% for message in get_flashed_messages() %}
<div class="container alert alert-info">
  {{ message }}
</div>
{% endfor %}
{% endblock flash %}

{% block content %} {% endblock content %}
</body>
{% endblock body %}
</html>